updated installer

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,57 +1,154 @@
 #!/usr/bin/env bash
+BASEDIR=$(pwd dirname $0)
+source $BASEDIR/zsh/colors.zsh
+source $BASEDIR/zsh/functions.zsh
 
-BASEDIR=$(dirname $0)
-BASEPATH=$(pwd $BASEDIR)
-INSTALLPATH=~
-DOTFILE=.dotfiles
+## Setup values
+#######################################
 
-# include
-source $BASEPATH/zsh/colors.zsh
-source $BASEPATH/zsh/functions.zsh
+# File created by installer
+DOTFILENAME=.dotfiles
 
-function initialize {
-	printf "################################################################################\n"
-	printf "### Dotfiles                                                                 ###\n"
-	printf "################################################################################\n"
-	touch $INSTALLPATH/$DOTFILE
+# Directory used to install dotfiles
+INSTALLDIR=~
+
+# Default groups to install
+DGRPS=( base-devel )
+
+# Default packages to auto install
+DPKGS=( git vim cmake clang sublime-text-dev )
+
+## Constructor
+#######################################
+function Bootstrapper {
+	InstallPackages
+	SymlinkFiles
 }
 
-function finalize {
-	echo "done" > $INSTALLPATH/$DOTFILE
+
+## Packages
+#######################################
+CMDEXPAGRP="pacman -Sg"
+CMDFINDPKG="pacman -Qi"
+CMDINSTPKG="pacman -S --noconfirm"
+
+PKGS=()
+function InstallPackages {
+	info "Checking packages"
+	for grp in ${DGRPS[*]}; do
+		CheckGroup $grp
+	done
+
+	for pkg in ${DPKGS[*]}; do
+		CheckPackage $pkg
+	done
+
+echo "$(joinstr " " "${PKGS[@]}")"
+	SPKGS="$(joinstr " " "${PKGS[@]}")"
+	if ! [ "$SPKGS" == "" ]; then
+		if sudo $CMDINSTPKG $SPKGS; then
+			success "success installing"
+		else
+			error "error installing"
+		fi
+	fi
 }
 
-function symlink {
-	TEMPLATES=$BASEPATH/**/*.tmpl
-	for template in $TEMPLATES; do
-		filename=${template/\.tmpl/}
-		if [ ! -f $filename ]; then
-			progress $template
-			symlink=""
-			while read line || [[ -n $line ]]; do
-				if [[ $line =~ %(.+)% ]]; then
-					varname="${BASH_REMATCH[1]}"
-					question "Enter value for <${varname}>: "
-					read -s varvalue < /dev/tty
-					line="${line//%$varname%/$varvalue}"
-				fi
-				symlink="$symlink$line\n"
-			done < $template
+function CheckGroup {
+	GRPNAME=$1
+	progress "Group $CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET: expanding..."
+	GRPPKGS=("$($CMDEXPAGRP $GRPNAME)")
 
-			printf "$symlink" > $filename
-			success $template
+	missing=false
+	for pkg in $GRPPKGS; do
+		if [ ! $pkg == $GRPNAME ] && ! $CMDFINDPKG $pkg > /dev/null; then
+			missing=true
 		fi
 	done
 
-	SYMLINKS=$BASEPATH/**/*.symlink
+	if $missing; then
+		if confirm "Group $CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET: continue installation?"; then
+			success "Group $CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET: installation pending"
+			PKGS+=( $GRPNAME )
+		else
+			success "Group $CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET: not added"
+		fi
+	else
+		success "Group $CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET: already installed"
+	fi
+}
+
+function CheckPackage {
+	PKGNAME=$1
+	progress "Package $CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: looking..."
+	if $CMDFINDPKG $PKGNAME > /dev/null; then
+		success "Package $CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: already installed."
+	else
+		if confirm "Package $CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: continue installation?"; then
+			success "Package $CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: installation pending."
+			PKGS+=($PKGNAME)
+		else
+			success "Package $CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: not added."
+		fi
+	fi
+}
+
+
+## Symlinking
+#######################################
+function SymlinkFiles {
+	info "Checking symlinks"
+
+	TEMPLATES=$BASEDIR/**/*.tmpl
+	for template in $TEMPLATES; do
+		ParseConfigTemplate $template
+	done
+
+	SYMLINKS=$BASEDIR/**/*.symlink
 	for symlink in $SYMLINKS; do
-		filename=${symlink/\.symlink/}
-		progress $symlink
-		ln -fs $(readlink -f $symlink) $INSTALLPATH/.$(basename $filename)
-		success $symlink
+		SymlinkConfig $symlink
 	done
 }
 
-# run
-initialize
-symlink
-finalize
+function ParseConfigTemplate {
+	template=$1
+	filename=${template/\.tmpl/}
+	tplbase=$(basename $template)
+	progress "Template $CYELLOW[$CRESET$CGRAY$tplbase$CRESET$CYELLOW]$CRESET: looking..."
+
+	if [ ! -f $filename ]; then
+		symlink=""
+		while read line || [[ -n $line ]]; do
+			if [[ $line =~ %(.+)% ]]; then
+				varname="${BASH_REMATCH[1]}"
+				question "Template $CYELLOW[$CRESET$CGRAY$tplbase$CRESET$CYELLOW]$CRESET: <${varname}>: "
+				line="${line//%$varname%/$REPLY}"
+			fi
+			symlink="$symlink$line\n"
+		done < $template
+
+		printf "$symlink" > $filename
+		success "Template $CYELLOW[$CRESET$CGRAY$tplbase$CRESET$CYELLOW]$CRESET: generated"
+	else
+		success "Template $CYELLOW[$CRESET$CGRAY$tplbase$CRESET$CYELLOW]$CRESET: already generated"
+	fi
+}
+
+function SymlinkConfig {
+	symlink=$1
+	filename=${symlink/\.symlink/}
+	symbase=$(basename $filename)
+	progress "Symlink $CYELLOW[$CRESET$CGRAY$symbase$CRESET$CYELLOW]$CRESET: looking..."
+	ln -fs $(readlink -f $symlink) $INSTALLDIR/.$symbase
+	success "Symlink $CYELLOW[$CRESET$CGRAY$symbase$CRESET$CYELLOW]$CRESET: symlink created"
+}
+
+
+################################################################################
+### Bootstrap                                                                ###
+### ------------------------------------------------------------------------ ###
+### translate long args to short args                                        ###
+### thanks to:                                                               ###
+### https://gist.github.com/adamhotep/895cebf290e95e613c006afbffef09d7       ###
+################################################################################
+Bootstrapper 
