added wine stuff and updated install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 shopt -s globstar
 BASEDIR=$(dirname `readlink -f $0`)
+DOTFILES=$BASEDIR
 source $BASEDIR/zsh/colors.zsh
 source $BASEDIR/zsh/functions.zsh
 
@@ -22,7 +23,7 @@ DPKGS=( git vim cmake clang gtest dtags sublime-text-dev )
 ## Constructor
 #######################################
 function Bootstrapper {
-	# InstallPackages
+	InstallPackages
 	SymlinkFiles
 }
 
@@ -30,12 +31,14 @@ function Bootstrapper {
 ## Packages
 #######################################
 CMDEXPAGRP="pacman -Sg"
-CMDFINDPKG="pacman -Qi"
+CMDFINDPKG="pacman -Qs"
 CMDINSTPKG="pacman -S --noconfirm"
 
 PKGS=()
 function InstallPackages {
-	info "Checking packages"
+	PREFIX="$CYELLOW[$CRESET$CGRAY"packages"$CRESET$CYELLOW]$CRESET"
+	progress "$PREFIX: Checking ..."
+
 	for grp in ${DGRPS[*]}; do
 		CheckGroup $grp
 	done
@@ -44,52 +47,45 @@ function InstallPackages {
 		CheckPackage $pkg
 	done
 
-echo "$(joinstr " " "${PKGS[@]}")"
 	SPKGS="$(joinstr " " "${PKGS[@]}")"
 	if ! [ "$SPKGS" == "" ]; then
-		if sudo $CMDINSTPKG $SPKGS; then
-			success "success installing"
-		else
-			error "error installing"
+		info "$PREFIX: Installing ...\n"
+		if ! sudo $CMDINSTPKG $SPKGS; then
+			error "$PREFIX: Error"
 		fi
 	fi
+
+	success "$PREFIX: Installed ${#PKGS[@]} new packages"
 }
 
 function CheckGroup {
 	GRPNAME=$1
-	progress "Group $CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET: expanding..."
 	GRPPKGS=("$($CMDEXPAGRP $GRPNAME)")
 
-	missing=false
 	for pkg in $GRPPKGS; do
-		if [ ! $pkg == $GRPNAME ] && ! $CMDFINDPKG $pkg > /dev/null; then
-			missing=true
+		if [ ! $pkg == $GRPNAME ]; then
+			CheckPackage $pkg "$CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET"
 		fi
 	done
+}
 
-	if $missing; then
-		if confirm "Group $CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET: continue installation?"; then
-			success "Group $CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET: installation pending"
-			PKGS+=( $GRPNAME )
-		else
-			success "Group $CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET: not added"
-		fi
-	else
-		success "Group $CYELLOW[$CRESET$CGRAY$GRPNAME$CRESET$CYELLOW]$CRESET: already installed"
-	fi
+function _internalCheckPackage {
+	PGKNAME="$1"
+	# Search for the package with regex
+	CHECK="$($CMDFINDPKG "$PKGNAME" | grep "local" | grep "$PKGNAME ")"
+	if [ -z "$CHECK" ]; then echo 1; return;
+	else echo 0; return; fi
 }
 
 function CheckPackage {
 	PKGNAME=$1
-	progress "Package $CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: looking..."
-	if $CMDFINDPKG $PKGNAME > /dev/null; then
-		success "Package $CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: already installed."
-	else
-		if confirm "Package $CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: continue installation?"; then
-			success "Package $CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: installation pending."
+	GROUP=$2
+	progress "$GROUP$CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: looking ..."
+	if [[ $(_internalCheckPackage "$PKGNAME") == 1 ]]; then
+	# if [[ $(_isInstalled "$PKGNAME") == 1 ]]; then
+		if confirm "$GROUP$CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: continue installation?"; then
+			success "$GROUP$CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: installation pending."
 			PKGS+=($PKGNAME)
-		else
-			success "Package $CYELLOW[$CRESET$CGRAY$PKGNAME$CRESET$CYELLOW]$CRESET: not added."
 		fi
 	fi
 }
@@ -98,7 +94,8 @@ function CheckPackage {
 ## Symlinking
 #######################################
 function SymlinkFiles {
-	info "Checking symlinks"
+	PREFIX="$CYELLOW[$CRESET$CGRAY"symlinks"$CRESET$CYELLOW]$CRESET"
+	progress "$PREFIX: Checking ..."
 
 	TEMPLATES=$BASEDIR/**/*.tmpl
 	for template in $TEMPLATES; do
@@ -109,37 +106,39 @@ function SymlinkFiles {
 	for symlink in $SYMLINKS; do
 		SymlinkDotfile $INSTALLDIR $symlink
 	done
-	
-	CONFIGPATH=$BASEDIR/config
-	SYMLINKS=$CONFIGPATH/**/*.symlink-config
-	for symlink in $SYMLINKS; do
-		basepath=$(dirname $symlink)
-		installpath=${basepath//$CONFIGPATH\//}
-		SymlinkConfig $INSTALLDIR/.config/$installpath $symlink
-	done
+
+	# CONFIGPATH=$BASEDIR/config
+	# SYMLINKS=$CONFIGPATH/**/*.symlink-config
+	# for symlink in $SYMLINKS; do
+	# 	basepath=$(dirname $symlink)
+	# 	installpath=${basepath//$CONFIGPATH\//}
+	# 	SymlinkConfig $INSTALLDIR/.config/$installpath $symlink
+	# done
+
+	success "$PREFIX: Finished"
 }
 
 function ParseConfigTemplate {
-	template=$1
-	filename=${template/\.tmpl/}
-	tplbase=$(basename $template)
-	progress "Template $CYELLOW[$CRESET$CGRAY$tplbase$CRESET$CYELLOW]$CRESET: looking..."
+	TMPL=$1
+	FILE=${template/\.tmpl/}
+	TMPLBASE=$(basename $TMPL)
 
-	if [ ! -f $filename ]; then
-		symlink=""
+	PREFIX="$CYELLOW[$CRESET$CGRAY$TMPLBASE$CRESET$CYELLOW]$CRESET"
+	progress "$PREFIX: looking ..."
+
+	if ! [ -f $FILE ]; then
+		LINK=""
 		while read line || [[ -n $line ]]; do
 			if [[ $line =~ %(.+)% ]]; then
-				varname="${BASH_REMATCH[1]}"
-				question "Template $CYELLOW[$CRESET$CGRAY$tplbase$CRESET$CYELLOW]$CRESET: <${varname}>: "
-				line="${line//%$varname%/$REPLY}"
+				VNAME="${BASH_REMATCH[1]}"
+				question "$PREFIX: <${VNAME}>: "
+				line="${line//%$VNAME%/$REPLY}"
 			fi
-			symlink="$symlink$line\n"
-		done < $template
+			LINK="$LINK$line\n"
+		done < $TMPL
 
-		printf "$symlink" > $filename
-		success "Template $CYELLOW[$CRESET$CGRAY$tplbase$CRESET$CYELLOW]$CRESET: generated"
-	else
-		success "Template $CYELLOW[$CRESET$CGRAY$tplbase$CRESET$CYELLOW]$CRESET: already generated"
+		printf "$LINK" > $FILE
+		success "$PREFIX: Generated"
 	fi
 }
 
